version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: coffee_service
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d coffee_service"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ../database/migrations:/migrations
    entrypoint: [ "sh", "-c", "sleep 5 && migrate -path=/migrations -database postgres://root:pwd@postgres:5432/coffee_service?sslmode=disable up" ]
    depends_on:
      - postgres

volumes:
  db-data:
